DEF_TREE_ERR(TREE_NO_ERR, "There is no error")
DEF_TREE_ERR(TREE_NULL_PTR_ERR, "Pointer on tree is NULL")
DEF_TREE_ERR(TREE_NULL_NODE_PTR_ERR, "Node pointer is NULL")
DEF_TREE_ERR(TREE_NODE_IS_FULL, "Node has both children")
DEF_TREE_ERR(TREE_MEM_ALLOC_ERR, "Error at memory allocation")
DEF_TREE_ERR(TREE_TRAVERSE_ERR, "Error at traverse function")
DEF_TREE_ERR(TREE_NULL_TRAVERSE_FUNCTION_ERR, "Null traverse function pointer")
#undef DEF_TREE_ERR
